### ISSUE TITLE
Add a task

### ISSUE THREAD

**Issue by MuhammadHoze** [AY2021S1-CS2113-T14-3/tp#7]
As a user i would like to be able to keep track of my tasks.

**Comment by iamchenjiajun** [comment]
Adding a task
Format: add TASK_NAME [by/DD-MM-YYYY-HH:MM] [at/DD-MM-YYYY-HH:MM] [p/PRIORITY_NUMBER] [class/CLASSIFICATION]
Adds a task with a given task name.
Example: add tP meeting,
add tP meeting by/16-09-23:59 at/15-09-2020-11:00,
add tP meeting by/16-09-23:59 at/15-09-2020-11:00 p/1
add tP meeting by/16-09-23:59 at/15-09-2020-11:00 p/1 class/project
Expected output: 
Noted. I’ve added this task.
tP meeting by: 16-09-2020-23:59 @ 15-09-2020-11:00
